apiVersion: v1
kind: Service
metadata:
  name: thumbnailer-service
  labels:
    app: thumbnailer
spec:
  selector:
    app: thumbnailer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
